LABELS_MAPPING = {
    0: 'PE',
    1: 'PET',
    2: 'PP',
    3: 'PS - SAN',
    4: 'PVC',
    5: 'PU - PUR',
    6: 'PC',
    7: 'ABS',
    8: 'CA',
    9: 'PA',
    10: 'Acrylic',
    11: 'EVA - PEVA',
    12: 'Rubber',
    13: 'PES',
    14: 'Silicone',
    15: 'Quartz sand',
    16: 'Animal fur',
    17: 'Cellulose',
    18: 'Coal',
}